security:
    password_hashers:
        App\Entity\User:
            algorithm: auto  
            cost: 12  

    firewalls:
        login:
            pattern: ^/$
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_liste_index
            logout:
                path: /logout
                target: /
            provider: app_user_provider

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
