controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_liste_article_toggle:
    path: /liste_article/toggle/{id}
    controller: App\Controller\ListeArticleController::toggleEstAchete
    methods: POST